### ISSUE TITLE
do not use HTTP headers for getting the IP address

### ISSUE THREAD

**Issue by DanielRuf** [wp-statistics/wp-statistics#135]
Only `REMOTE_ADDR` is safe against changes by users.
The others can be easily spoofed.

https://github.com/wp-statistics/wp-statistics/blob/73f066d51baf54efd989d13c38ee4842141efbc1/includes/classes/class-wp-statistics.php#L864-L871

**Comment by mostafasoufi** [comment]
Hi @DanielRuf,

By default we use the  `REMOTE_ADDR` for getting IP addresses.

https://github.com/wp-statistics/wp-statistics/blob/73f066d51baf54efd989d13c38ee4842141efbc1/includes/classes/class-wp-statistics.php#L847-L850

**Comment by DanielRuf** [comment]
Sure, but using others is not recommended at all.

**Comment by adlerweb** [comment]
REMOTE_ADDR usually only works on simple deployment using a local webserver. As soon as Docker, CDNs or reverse proxies are involved REMOTE_ADDR is either unusable (local/upstream IP) or reconstructed using the mentioned HTTP-headers using a webserver module. Removing it would break tracking in a lot of aforementioned setups. It should be pretty easy to drop headers on server level if required.

**Comment by DanielRuf** [comment]
No, also correctly setup servers and containers can get REMOTE_ADDR. The others can be set by clients as they want (spoofing and other attacks).

**Comment by mostafasoufi** [comment]
Fixed. https://github.com/wp-statistics/wp-statistics/issues/200 https://github.com/wp-statistics/wp-statistics/issues/98

**Comment by DanielRuf** [comment]
Where was this changed in your code?

**Comment by adlerweb** [comment]
Skipping over the changes this still prefers REMOTE_ADDR over everything else without any option to contigure it. As such this still won't work with setups like docker or similar.

**Comment by mostafasoufi** [comment]
@DanielRuf 
Yes, in general, we've just some changes in `get_IP()`.

@adlerweb 
Unfortunately, we don't have any environment for testing in Docker, can you have a review?

Generally, the get IP is one of the important methods in the plugin and we need to make sure in another environment that works fine.

Please let us if there is anything.

**Comment by DanielRuf** [comment]
> Unfortunately, we don't have any environment for testing in Docker, can you have a review?

You can test with Travis CI and Circle CI containers.

**Comment by DanielRuf** [comment]
https://github.com/wp-statistics/wp-statistics/commit/9781d714de6ef335dc4721b867b8ac5c9030f988
